### ISSUE TITLE
BUG - Profile setting error - unix/windows Upercase

### ISSUE THREAD

**Issue by thisissobhy** [yassinrais/sakura-panel#40]
````bash
PHP Fatal error:  Uncaught Phalcon\\Mvc\\Dispatcher\\Exception: Sakura\\Controllers\\Member\\ProfileSettingsController handler class cannot be loaded in /app/app/Bootstrap.php:111\nStack trace:\n#0 [internal function]: Phalcon\\Mvc\\Dispatcher->throwDispatchException()\n#1 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#2 /app/app/Bootstrap.php(111): Phalcon\\Mvc\\Application->handle()\n#3 /app/app/Bootstrap.php(96): Sakura\\Bootstrap->getOutput()\n#4 /app/public/index.php(9): Sakura\\Bootstrap->run()\n#5 {main}\n  thrown in /app/app/Bootstrap.php on line 111, referer: http://localhost:8000/admin/users
````

**Comment by yassinrais** [comment]
🟩
